[[commands]]
prompt = "Run nixos-rebuild for local system?"
command = ["sudo", "nixos-rebuild", "switch", "--flake", "path:.#"]
precheck = ["sudo", "test", "-s", "/etc/nixos/secrets/hill.hashed-password"]
needs_sudo = true

[[commands]]
prompt = "Run nixos-rebuild for hetzner?"
command = ["nixos-rebuild", "switch", "--flake", "path:.#hetzner", "--target-host", "root@server"]
precheck = ["ssh", "-o", "BatchMode=yes", "-o", "ConnectTimeout=10", "root@server", "test -s /etc/nixos/secrets/nextcloud-admin-pass"]

[[commands]]
prompt = "Run nixos-rebuild for laptop?"
command = ["nixos-rebuild", "switch", "--flake", "path:.#laptop", "--target-host", "root@laptop"]

[[commands]]
prompt = "Run nixos-rebuild for localserver?"
command = ["nixos-rebuild", "switch", "--flake", "path:.#localserver", "--target-host", "root@localserver"]

[[commands]]
prompt = "Run nixos-rebuild for thinkcentre?"
command = ["nixos-rebuild", "switch", "--flake", "path:.#thinkcentre", "--target-host", "root@thinkcentre"]

[[commands]]
prompt = "Build standalone Home Manager config?"
command = ["nix", "build", "path:.#homeConfigurations.hill.activationPackage", "--no-link", "--print-build-logs"]

[[commands]]
prompt = "Build WSL tarball?"
command = ["sudo", "nix", "run", "path:.#nixosConfigurations.wsl.config.system.build.tarballBuilder"]
needs_sudo = true
