# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["ata_piix" "virtio_pci" "virtio_scsi" "xhci_pci" "sd_mod" "sr_mod"];
  boot.initrd.kernelModules = ["dm-snapshot"];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/e3f14fea-e17f-404d-a914-0e91e545cc99";
    fsType = "ext4";
  };

  fileSystems."/mnt/volume" = {
    device = "/dev/disk/by-uuid/aaee5682-3fa4-42e8-af6b-4324c55eccde";
    fsType = "ext4";
    options = ["nofail"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D9D9-BE91";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/var/lib/nextcloud/data/hill" = {
    device = "/mnt/volume/nextcloud/data/hill";
    fsType = "none";
    options = ["bind"];
  };

  swapDevices = [
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  # networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens10.useDHCP = lib.mkDefault true;
  networking.interfaces.ens3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
