# Do not modify this file! It was generated by nixos-generate-config on macbook.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/hardware/network/broadcom-43xx.nix")
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ahci"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [];
      luks.devices."luks-e59e766c-4dde-4533-9bf5-c39ad6c5d51f".device = "/dev/disk/by-uuid/e59e766c-4dde-4533-9bf5-c39ad6c5d51f";
    };
    kernelModules = ["kvm-intel"];
    extraModulePackages = [];
  };

  fileSystems = {
    "/" = {
      device = "/dev/mapper/luks-e59e766c-4dde-4533-9bf5-c39ad6c5d51f";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/2B61-9B8E";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };
  };

  swapDevices = [
    {device = "/dev/mapper/luks-28f911f1-d35f-452f-89fa-b705650f5227";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
